# Generated by Django 3.0.8 on 2020-07-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0013_auto_20200723_1519'),
        ('HUMANRESOURCE', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'EMPLOYEE | EMPLOYEE GENERAL INFO'},
        ),
        migrations.CreateModel(
            name='EmployeePersonalInfo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Employee Personal Info ID')),
                ('religion', models.CharField(choices=[], max_length=50, verbose_name='Religion')),
                ('blood_group', models.CharField(choices=[], max_length=50, verbose_name='Blood Group')),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Height (cm.)')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Weight (cm.)')),
                ('military_status', models.CharField(choices=[], max_length=50, verbose_name='Military Status')),
                ('marital_status', models.CharField(choices=[], max_length=50, verbose_name='Marital Status')),
                ('gender', models.CharField(choices=[], max_length=50, verbose_name='Gender')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HUMANRESOURCE.Employee', verbose_name='Employee')),
                ('living_arrangement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.LivingArrangement', verbose_name='Living Arrangement')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.Nationality', verbose_name='Nationality')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.Race', verbose_name='Race')),
            ],
            options={
                'verbose_name_plural': 'EMPLOYEE | EMPLOYEE PERSONAL INFO',
                'ordering': ['employee__first_name', 'employee__last_name'],
            },
        ),
    ]
