# Generated by Django 3.0.8 on 2020-07-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUMANRESOURCE', '0002_auto_20200723_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='blood_group',
            field=models.CharField(choices=[('Blood Group O', 'Blood Group O'), ('Blood Group A', 'Blood Group A'), ('Blood Group B', 'Blood Group B'), ('Blood Group AB', 'Blood Group AB')], max_length=50, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=50, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='military_status',
            field=models.CharField(choices=[('Not yet served', 'Not yet served'), ('Served', 'Served'), ('Exempted', 'Exempted')], max_length=50, verbose_name='Military Status'),
        ),
        migrations.AlterField(
            model_name='employeepersonalinfo',
            name='religion',
            field=models.CharField(choices=[('African Traditional Religion', 'African Traditional Religion'), ('Bahai', 'Bahai'), ('Buddhism', 'Buddhism'), ('Cao Dai', 'Cao Dai'), ('Chinese Traditional Religion', 'Chinese Traditional Religion'), ('Christainity', 'Christianity'), ('Ethnic Religion', 'Ethnic Religion'), ('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Jainism', 'Jainism'), ('Judaism', 'Judaism'), ('Neo-Paganism', 'Neo-Paganism'), ('Non - Religious', 'Non - Religious'), ('Rastafari', 'Rastafari'), ('Shinto', 'Shinto'), ('Sikhism', 'Sikhism'), ('Spiritsm', 'Spiritsm'), ('Tenrikyo', 'Tenrikyo'), ('Unitarian Universalism', 'Unitarium Universalism'), ('Zoroastianism', 'Zoroastianism')], max_length=50, verbose_name='Religion'),
        ),
    ]
