# Generated by Django 3.0.8 on 2020-07-26 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HUMANRESOURCE', '0003_auto_20200726_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAddress',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Employee Address ID')),
                ('address_type', models.CharField(choices=[('ที่อยู่ปัจจุบัน', 'ที่อยู่ปัจจุบัน'), ('ที่อยู่ตามทะเบียนบ้าน', 'ที่อยู่ตามทะเบียนบ้าน'), ('ที่อยู่อื่นๆ', 'ที่อยู่อื่นๆ')], max_length=100, verbose_name='Address Type')),
                ('address_line_1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='Address Line 2')),
                ('sub_district', models.CharField(max_length=50, verbose_name='Sub District / Tumbol')),
                ('district', models.CharField(max_length=50, verbose_name='District')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('postal_code', models.CharField(max_length=10, verbose_name='ZIP / Postal Code')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='HUMANRESOURCE.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name_plural': 'EMPLOYEE | EMPLOYEE ADDRESS INFO',
                'ordering': ['employee__first_name', 'employee__last_name'],
            },
        ),
    ]
