# Generated by Django 3.0.8 on 2020-07-20 13:52

import WAREHOUSE.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PURCHASE', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLotNumber',
            fields=[
                ('id', models.CharField(default=WAREHOUSE.models.increment_lot_number_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Product Lot No.')),
                ('original_lot_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Original Lot No.')),
                ('received_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Received Date')),
                ('receiving_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Receiving Amount')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Remaining Amount')),
                ('manufactured_date', models.DateField(verbose_name='Manufactured Date')),
                ('expired_date', models.DateField(verbose_name='Expired Date')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Unit Cost')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASE.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'PRODUCT | PRODUCT LOT NUMBER',
                'ordering': ['-id'],
            },
        ),
    ]
