# Generated by Django 3.0.8 on 2020-07-06 05:18

import PURCHASE.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SETTINGS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(default=PURCHASE.models.increment_supplier_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Supplier ID')),
                ('name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('supplier_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.SupplierType', verbose_name='Supplier Type')),
            ],
            options={
                'verbose_name_plural': 'SUPPLIER | SUPPLIER GENERAL INFO',
                'ordering': ['id'],
            },
        ),
    ]
