# Generated by Django 3.0.8 on 2020-07-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PURCHASE', '0002_supplieraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierContactPerson',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Supplier Contact Person ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Fullname')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASE.Supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name_plural': 'SUPPLIER | SUPPLIER CONTACT PERSON INFO',
                'ordering': ['supplier__id'],
            },
        ),
    ]
