# Generated by Django 3.0.8 on 2020-07-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0003_paymentterm'),
        ('PURCHASE', '0003_suppliercontactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPaymentTerm',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Supplier Payment Term ID')),
                ('credit_day', models.PositiveIntegerField(default=0, verbose_name='Credit Day')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Credit Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.PaymentTerm', verbose_name='Payment Term')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASE.Supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name_plural': 'SUPPLIER | SUPPLIER PAYMENT TERM INFO',
                'ordering': ['supplier__id'],
            },
        ),
    ]
