# Generated by Django 3.0.8 on 2020-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Country ID')),
                ('name', models.CharField(max_length=200, verbose_name='Country Name')),
            ],
            options={
                'verbose_name_plural': 'COUNTRY | COUNTRY LIST',
                'ordering': ['name'],
            },
        ),
    ]
