# Generated by Django 3.0.8 on 2020-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Payment Term ID')),
                ('payment_term', models.CharField(max_length=100, verbose_name='Payment Term')),
            ],
            options={
                'verbose_name_plural': 'PAYMENT TERM | PAYMENT TERM',
                'ordering': ['payment_term'],
            },
        ),
    ]
