# Generated by Django 3.0.8 on 2020-07-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0003_paymentterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingMaterial',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Packing Material ID')),
                ('packing_material', models.CharField(max_length=20, verbose_name='Packing Material')),
            ],
            options={
                'verbose_name_plural': 'PRODUCT | PACKING MATERIAL',
                'ordering': ['packing_material'],
            },
        ),
        migrations.CreateModel(
            name='PackingType',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Packing Type ID')),
                ('packing_type', models.CharField(max_length=20, verbose_name='Packing Type')),
            ],
            options={
                'verbose_name_plural': 'PRODUCT | PACKING TYPE',
                'ordering': ['packing_type'],
            },
        ),
    ]
