# Generated by Django 3.0.8 on 2020-07-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0005_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisitionStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Purchase Requisition Status ID')),
                ('purchase_requisition_status', models.CharField(max_length=20, verbose_name='Purchase Requisition Status')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | PURCHASE REQUISITION | PURCHASE REQUISITION STATUS',
                'ordering': ['purchase_requisition_status'],
            },
        ),
    ]
