# Generated by Django 3.0.8 on 2020-07-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0006_purchaserequisitionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Purchase Requisition Status ID')),
                ('quotation_status', models.CharField(max_length=20, verbose_name='Quotation Status')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | QUOTATION | QUOTATION STATUS',
                'ordering': ['quotation_status'],
            },
        ),
    ]
