# Generated by Django 3.0.8 on 2020-07-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0007_quotationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_line_1',
            field=models.CharField(default=' ', max_length=50, verbose_name='Address Line 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default=' ', max_length=100, verbose_name='Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.CharField(default=' ', max_length=50, verbose_name='District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='supports@chemmin.net', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(default='02-175-2152', max_length=20, verbose_name='Fax Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default='02-175-2131', max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(default='10540', max_length=10, verbose_name='ZIP / Postal Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.CharField(default='Samut Prakarn', max_length=50, verbose_name='Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sub_district',
            field=models.CharField(default='Rachatewa', max_length=50, verbose_name='Sub District / Tumbol'),
            preserve_default=False,
        ),
    ]
