# Generated by Django 3.0.8 on 2020-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0008_auto_20200715_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderStatus',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Sales Order Status ID')),
                ('sales_order_status', models.CharField(max_length=20, verbose_name='Sales Order Status')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | SALES ORDER | SALES ORDER STATUS',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='quotationstatus',
            options={'ordering': ['id'], 'verbose_name_plural': 'SETTINGS | QUOTATION | QUOTATION STATUS'},
        ),
        migrations.AlterField(
            model_name='quotationstatus',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Quotation Status ID'),
        ),
    ]
