# Generated by Django 3.0.8 on 2020-07-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0010_dailyreportcontactmethod_dailyreporttype_purchaseorderstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequisitionstatus',
            options={'ordering': ['id'], 'verbose_name_plural': 'SETTINGS | PURCHASE REQUISITION | PURCHASE REQUISITION STATUS'},
        ),
    ]
