# Generated by Django 3.0.8 on 2020-07-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0011_auto_20200720_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingArrangement',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Living Arrangement ID')),
                ('living_arrangement', models.CharField(max_length=20, verbose_name='Living Arrangement')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | EMPLOYEE | LIVING ARRANGEMENT',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Nationality ID')),
                ('nationality', models.CharField(max_length=20, verbose_name='Nationality')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | EMPLOYEE | NATIONALITY',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Race ID')),
                ('race', models.CharField(max_length=20, verbose_name='Race')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | EMPLOYEE | RACE',
                'ordering': ['id'],
            },
        ),
    ]
