# Generated by Django 3.0.8 on 2020-07-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0012_livingarrangement_nationality_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Department ID')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | ORGANIZATION | DEPARTMENT',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Division ID')),
                ('division', models.CharField(max_length=100, verbose_name='Division')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | ORGANIZATION | DIVISION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Position ID')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | ORGANIZATION | POSITION',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Section ID')),
                ('section', models.CharField(max_length=100, verbose_name='Section')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.Department', verbose_name='Department')),
            ],
            options={
                'verbose_name_plural': 'SETTINGS | ORGANIZATION | SECTION',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.Division', verbose_name='Division'),
        ),
    ]
