# Generated by Django 3.0.8 on 2020-07-11 04:15

import SALES.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=SALES.models.increment_customer_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Customer ID')),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'CUSTOMER | CUSTOMER GENERAL INFO',
                'ordering': ['id'],
            },
        ),
    ]
