# Generated by Django 3.0.8 on 2020-07-12 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0005_company'),
        ('SALES', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'verbose_name_plural': 'CUSTOMER | CUSTOMER GENERAL INFO'},
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Customer Address ID')),
                ('address_name', models.CharField(max_length=100, verbose_name='Address Name')),
                ('address_line_1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line 2')),
                ('sub_district', models.CharField(max_length=100, verbose_name='Sub District')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('province', models.CharField(max_length=100, verbose_name='Province')),
                ('postal_code', models.CharField(max_length=10, verbose_name='ZIP/Postal Code')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.Country', verbose_name='Country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name_plural': 'CUSTOMER | CUSTOMER ADDRESS INFO',
                'ordering': ['customer__id'],
            },
        ),
    ]
