# Generated by Django 3.0.8 on 2020-07-12 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SALES', '0002_auto_20200712_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContactPerson',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Customer Contact Person ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Fullname')),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name_plural': 'CUSTOMER | CUSTOMER CONTACT PERSON INFO',
                'ordering': ['customer__id'],
            },
        ),
    ]
