# Generated by Django 3.0.8 on 2020-07-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETTINGS', '0005_company'),
        ('SALES', '0003_customercontactperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentTerm',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Customer Payment Term ID')),
                ('credit_day', models.PositiveIntegerField(default=0, verbose_name='Credit Day')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Credit Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.Customer', verbose_name='Customer')),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.PaymentTerm', verbose_name='Payment Term')),
            ],
            options={
                'verbose_name_plural': 'CUSTOMER | CUSTOMER PAYMENT TERM INFO',
                'ordering': ['customer__id'],
            },
        ),
    ]
