# Generated by Django 3.0.8 on 2020-07-13 01:41

import SALES.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PURCHASE', '0005_product'),
        ('SETTINGS', '0006_purchaserequisitionstatus'),
        ('SALES', '0004_customerpaymentterm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.CharField(default=SALES.models.increment_purchase_requisition_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Purchase Requisition ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Purchase Requisition Date')),
                ('estimate_needed_date', models.DateField(verbose_name='Estimate Needed Date')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name_plural': 'PURCHASE REQUISITION - PURCHASE REQUISITION',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionStatusLog',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Purhase Requisition Status ID')),
                ('user', models.CharField(max_length=50, verbose_name='User')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('purchase_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.PurchaseRequisition', verbose_name='Purchase Requisition')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.PurchaseRequisitionStatus', verbose_name='Purchase Requisition Status')),
            ],
            options={
                'verbose_name_plural': 'PURCHASE REQUISITION - PURCHASE REQUISITION STATUS',
                'ordering': ['-purchase_requisition__id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Purchase Requisition Item ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Unit Price')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASE.Product', verbose_name='Product')),
                ('purchase_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.PurchaseRequisition', verbose_name='Purchase Requisition')),
            ],
            options={
                'verbose_name_plural': 'PURCHASE REQUISITION - PURCHASE REQUISITION ITEM',
                'ordering': ['-purchase_requisition__id'],
            },
        ),
    ]
