# Generated by Django 3.0.8 on 2020-07-14 07:51

import SALES.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PURCHASE', '0005_product'),
        ('HUMANRESOURCE', '0001_initial'),
        ('SETTINGS', '0007_quotationstatus'),
        ('SALES', '0005_purchaserequisition_purchaserequisitionitem_purchaserequisitionstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(default=SALES.models.increment_quotation_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Quotation ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Quotation Date')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('estimate_delivery_day', models.CharField(choices=[('1 - 3', '1 - 3'), ('3 - 5', '3 - 5'), ('5 - 7', '5 - 7'), ('7 - 10 ', '7 - 10 '), ('10 - 15 ', '10 - 15 '), ('15 - 30 ', '15 - 30 ')], max_length=20, verbose_name='Estimate Delivery Day')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Sub Total')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Discount')),
                ('after_discount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='After Discount')),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Value Added Tax')),
                ('net_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Net Total')),
                ('baht_text', models.CharField(default='', editable=False, max_length=200, verbose_name='Baht Text')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.Customer', verbose_name='Customer')),
                ('customer_billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.CustomerAddress', verbose_name='Customer Billing Address')),
                ('customer_contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.CustomerContactPerson', verbose_name='Customer Contact Person')),
                ('customer_payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SALES.CustomerPaymentTerm', verbose_name='Customer Payment Term')),
                ('sales_reps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HUMANRESOURCE.Employee', verbose_name='Sales Reps')),
            ],
            options={
                'verbose_name_plural': 'QUOTATION - QUOTATION',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='purchaserequisitionstatuslog',
            options={'ordering': ['-purchase_requisition__id'], 'verbose_name_plural': 'PURCHASE REQUISITION - PURCHASE REQUISITION STATUS LOG'},
        ),
        migrations.CreateModel(
            name='QuotationStatusLog',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Quotation Status Log ID')),
                ('user', models.CharField(max_length=50, verbose_name='User')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.Quotation', verbose_name='Quotation')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.QuotationStatus', verbose_name='Quotation Status')),
            ],
            options={
                'verbose_name_plural': 'QUOTATION - QUOTATION STATUS LOG',
                'ordering': ['-quotation__id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Quotation Item ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Unit Price')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASE.Product', verbose_name='Product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='SALES.Quotation', verbose_name='Quotation')),
            ],
            options={
                'verbose_name_plural': 'QUOTATION - QUOTATION ITEM',
                'ordering': ['-quotation__id'],
            },
        ),
        migrations.CreateModel(
            name='PersonInCharge',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Person In Charge ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.Customer', verbose_name='Customer')),
                ('sales_reps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HUMANRESOURCE.Employee', verbose_name='Sales Reps')),
            ],
            options={
                'verbose_name_plural': 'PERSON IN CHARGE | PERSON IN CHARGE',
            },
        ),
    ]
