# Generated by Django 3.0.8 on 2020-07-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SALES', '0006_auto_20200714_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='customer_payment_term',
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_term',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('CASH', 'CASH')], default='CASH', max_length=20, verbose_name='Payment Term'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='estimate_delivery_day',
            field=models.CharField(choices=[('1 - 3', '1 - 3'), ('1 - 5', '1 - 5'), ('1 - 7', '1 - 7'), ('1 - 10 ', '1 - 10 '), ('1 - 15 ', '1 - 15 '), ('1 - 30 ', '1 - 30 ')], max_length=20, verbose_name='Estimate Delivery Day'),
        ),
    ]
