# Generated by Django 3.0.8 on 2020-07-19 04:42

import SALES.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HUMANRESOURCE', '0001_initial'),
        ('SETTINGS', '0009_auto_20200719_1142'),
        ('PURCHASE', '0005_product'),
        ('SALES', '0007_auto_20200717_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.CharField(default=SALES.models.increment_sales_order_id, editable=False, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Sales Order ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sales Order Date')),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Delivery Date')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Sub Total')),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Value Added Tax')),
                ('net_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Net Total')),
                ('baht_text', models.CharField(default='', editable=False, max_length=200, verbose_name='Baht Text')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.Customer', verbose_name='Customer')),
                ('customer_billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_billing_address', to='SALES.CustomerAddress', verbose_name='Customer Billing Address')),
                ('customer_delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_delivery_address', to='SALES.CustomerAddress', verbose_name='Customer Delivery Address')),
                ('customer_payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.CustomerPaymentTerm', verbose_name='Customer Payment Term')),
                ('sales_reps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HUMANRESOURCE.Employee', verbose_name='Sales Reps')),
            ],
            options={
                'verbose_name_plural': 'SALES ORDER - SALES ORDER',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderStatusLog',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Sales Order Status Log ID')),
                ('user', models.CharField(max_length=50, verbose_name='User')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.SalesOrder', verbose_name='Sales Order')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.SalesOrderStatus', verbose_name='Sales Order Status')),
            ],
            options={
                'verbose_name_plural': 'SALES ORDER - SALES ORDER STATUS LOG',
                'ordering': ['-sales_order__id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Sales Order Item ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Unit Price')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASE.Product', verbose_name='Product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_items', to='SALES.SalesOrder', verbose_name='Sales Order')),
            ],
            options={
                'verbose_name_plural': 'SALES ORDER - SALES ORDER ITEM',
                'ordering': ['-sales_order__id'],
            },
        ),
    ]
