# Generated by Django 3.0.8 on 2020-07-19 14:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HUMANRESOURCE', '0001_initial'),
        ('SETTINGS', '0010_dailyreportcontactmethod_dailyreporttype_purchaseorderstatus'),
        ('PURCHASE', '0005_product'),
        ('SALES', '0008_salesorder_salesorderitem_salesorderstatuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Daily Report ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Daily Report Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('contact_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.DailyReportContactMethod', verbose_name='Contact Method')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.PersonInCharge', verbose_name='Customer')),
                ('customer_contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.CustomerContactPerson', verbose_name='Contact Person')),
                ('sales_reps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HUMANRESOURCE.Employee', verbose_name='Sales Reps')),
            ],
            options={
                'verbose_name_plural': 'DAILY REPORT - DAILY REPORT',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(verbose_name='Delivery Date'),
        ),
        migrations.CreateModel(
            name='DailyReportItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Daily Report Item ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Unit Price')),
                ('is_accept', models.NullBooleanField(verbose_name='Is Accept')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SALES.DailyReport', verbose_name='Daily Report')),
                ('daily_report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETTINGS.DailyReportType', verbose_name='Daily Report Type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PURCHASE.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'DAILY REPORT - DAILY REPORT ITEM',
                'ordering': ['-daily_report__id'],
            },
        ),
    ]
